### ISSUE TITLE
texdoc palatino or times both give unexpected result

### ISSUE THREAD

**Issue by jfbu** [TeX-Live/texdoc#1]
Test:

```console
$ texdoc -l palatino
 1 /usr/local/texlive/2018/texmf-dist/doc/latex/substitutefont/greek-palatino-didot.pdf
Enter number of file to view, RET to view 1, anything else to skip: 
```

This is a bit unexpected. Also

```console
$ texdoc -l times
 1 /usr/local/texlive/2018/texmf-dist/doc/latex/substitutefont/greek-times-artemisia.pdf
Enter number of file to view, RET to view 1, anything else to skip: 
```

These two (and others possibly, I have not tested more) should probably get aliased to ``psnfss2e``.

**Comment by wtsnjp** [comment]
Thanks for reporting that.

I found that aliases for those cases are already exist on [the texdoc.cnf](https://github.com/TeX-Live/texdoc/blob/master/texdoc.cnf#L295-L296) but *both commented out*. Do anyone knows why?

```toml
#alias palatino  = psnfss2e
#alias times     = psnfss2e
```

**Comment by wtsnjp** [comment]
Anyway, I fixed this (d1f6c7742b629089c869f443025fbad87ee7982c)

**Comment by kberry** [comment]
i committed the new texdoc.cnf to tl (r47255). it returns psnfss2e.pdf for all the .sty files in the package.

i think palatino and times were commented out (as several of the others are) because when there were no other matches, psnfss2e.pdf already won, due to the references in the catalogue entry. the greek substitutefont stuff is relatively recent.

it seems it would be better if the results for these package names did not depend on whether new files with those names get created, so i guess we should uncomment them all, even if it is redundant in some cases at the moment.

**Comment by wtsnjp** [comment]
> i guess we should uncomment them all

okay, will do.

**Comment by kberry** [comment]
i uncommented all the psnfss2e aliases for tl18. closing.
