### ISSUE TITLE
Ready for CTAN upload?

### ISSUE THREAD

**Issue by wtsnjp** [TeX-Live/texdoc#13]
I'm almost going to upload v3.0 to CTAN.

About the archive for CTAN, is the following structure enough? Or should I follow the TDS structure? Particulary, I'm quite not sure about the location of manpages.

```
.
├── COPYING
├── NEWS
├── README.md
├── doc
│   ├── man
│   │   ├── texdoc.1
│   │   └── texdoc.man1.pdf
│   ├── texdoc.pdf
│   └── texdoc.tex
├── script
│   ├── alias.tlu
│   ├── config.tlu
│   ├── constants.tlu
│   ├── functions.tlu
│   ├── main.tlu
│   ├── score.tlu
│   ├── search.tlu
│   ├── texdoc.tlu
│   ├── texdoclib.tlu
│   └── view.tlu
└── texdoc.cnf
```

I think above contains all files necessary for TeX Live distribution, but if it's not, please tell me that too.

**Comment by kberry** [comment]
There's no need for the man/ subdirectory, just doc/texdoc.1 is fine.

There's also no need to create texdoc.man1.pdf, since I generally create
the PDF for TL in any case. (And I don't think it's especially useful to
have that on CTAN.)

Regarding texdoc.cnf: not about where it is in your upload to CTAN (top
level, as you have it, seems good) but in TL. Right now there is a
top-top-level directory in TL texmf-dist/texdoc/ with that single file,
texdoc.cnf. This seems unnecessary and undesirable. (There are too many
tiny top-level directories in TL.)

So ... if TL puts texdoc.cnf into the scripts/ subdir
(texmf-dist/scripts/texdoc/) will texdoc still find it there?
If not, can we (you :) make it be so?

Thanks,
Karl

**Comment by wtsnjp** [comment]
I changed the structure as follows:

```
.
├── COPYING
├── NEWS
├── README.md
├── doc
│   ├── texdoc.1
│   ├── texdoc.pdf
│   └── texdoc.tex
├── script
│   ├── alias.tlu
│   ├── config.tlu
│   ├── constants.tlu
│   ├── functions.tlu
│   ├── main.tlu
│   ├── score.tlu
│   ├── search.tlu
│   ├── texdoc.tlu
│   ├── texdoclib.tlu
│   └── view.tlu
└── texdoc.cnf
```

I will upload v3.0 to CTAN soon enough!

**Comment by wtsnjp** [comment]
Talking about texdoc.cnf is a bit different from this issue, but anyway I will briefly response here.

> if TL puts texdoc.cnf into the scripts/ subdir (texmf-dist/scripts/texdoc/) will texdoc still find it there?

No, it won't. It require to change the Texdoc code, and this change can destroy the compatibility. So, we have to think twice before doing it, and I think just before releasing v3.0 is not the right time. Please kindly keep the position of texdoc.cnf at this point.

In the first place, putting texdoc.cnf under `scripts/` dir seems a bit wierd to me; texdoc.cnf is not a script file, and as a fact, I searched but there is no `*.cnf` file under the `texmf-dist/scripts`. I'm wondering there is another better place to put it.

Anyway, if we're going to continue this discussion, we should create another issue.

**Comment by kberry** [comment]
I'm sorry I didn't think of this before, but it would be much better if the texdoc *.tlu files were named with a texdoc- (or at least td-) prefix. E.g., texdoc-main.tlu, texdoc-functions.tlu, etc. Otherwise there could easily be a clash in the future. Could you work on this for the next release?

At any rate, I installed the release from CTAN (thanks!) into TL. Fingers crossed ...

**Comment by wtsnjp** [comment]
I think adding such prefixes is the last thing I'm going to do. Texdoc finds `texdoc/*.tlu` (not just `*.tlu`) so the `texdoc/` directory name plays a kind of role same as the prefix, so there's no need of the prefixes and it's looks ugly.

Even tough, using Kpathsea for loading Texdoc's own source code seems not making sense, so I'd like to change that behavior.

Anyway, this disscussion will move to #15. Thanks.
