### ISSUE TITLE
look in TEXMFCONFIG, not TEXMFVAR

### ISSUE THREAD

**Issue by kberry** [TeX-Live/texdoc#60]
with current, and older, texdoc, -v -f reports:

```
/usr/local/texlive/dev/texmf-dist/scripts/texdoc/texdoclib.tlu 3.2.2            
Configuration file(s):                                                          
    not found   /u/karl/.texlive2020/texmf-var/texdoc/texdoc-x86_64-linux.cnf   
    not found   /u/karl/.texlive2020/texmf-var/texdoc/texdoc.cnf                
    not found   /u/karl/.texlive2020/texmf-var/texdoc/texdoc-dist.cnf 
... more ...
```

My question is, why isn't ~/.../texmf-config shown? That would be a normal place to put per-user config files. texmf-var, on the other hand, is supposed to be for automatically generated cache files, i.e., if it is completely removed, everything in it should be able to be regenerated.

The texdoc manual says that everything in TEXMF is looked for, but only a few of the trees defined in TEXMF are actually shown. I think it would be better to just display all of them?

```
kpsewhich -expand-braces=\$TEXMF
/u/karl/.texlive2020/texmf-config:/u/karl/.texlive2020/texmf-var:/u/karl/texmf:!!/usr/local/texlive/dev/texmf-local:!!/usr/local/texlive/dev/texmf-config:!!/usr/local/texlive/dev/texmf-var:!!/usr/local/texlive/dev/texmf-dist     
```

**Comment by wtsnjp** [comment]
To get straight to the point, I think you are right. I will handle this.

> My question is, why isn't ~/.../texmf-config shown?

The technical answer for this is because it uses `kpse.expand_path()` for searching `$TEXMF/texdoc`. Only TEXMF trees that have `texdoc` dir are shown in the list for `-vf`. If you make the dir under `TEXMFCONFIG`, that should appear in the list.

https://github.com/TeX-Live/texdoc/blob/master/script/texdoclib-config.tlu#L278

> I think it would be better to just display all of them?

So, as a feature, config files in all of the TEXMF trees have been effective and will continue to work. I agree that it is better to show all of the places on that list, especially because it is the output for the `--verbose` option.

**Comment by wtsnjp** [comment]
With the above commit, it should show the complete list that you expect. Please have a try.
