### ISSUE TITLE
cache handling

### ISSUE THREAD

**Issue by norbusan** [TeX-Live/texdoc#8]
By now texdoc creates new cache files whenever the tlpd changes (even in version 3.0). Didn't we discuss that we drop the cache generation and always use the tlpdb directly?

**Comment by wtsnjp** [comment]
Yes, we did. And we (at least, I) decided to put this into the future work (not for v3.0).

The reason is simply it is too slow without the cache file.

On my own MBA (1.3 GHz Intel Core i5), searching a document:

* **WITHOUT** the cache file

```
$ time texdoc -lI gotoh
 1 /usr/local/texlive/2018/texmf-dist/doc/latex/gotoh/gotoh.pdf
   = Package documentation
 2 /usr/local/texlive/2018/texmf-dist/doc/latex/gotoh/README.md
   = Readme
texdoc -lI gotoh  2.25s user 0.06s system 97% cpu 2.369 total
```

* **WITH** the cache file

```
$ time texdoc -lI gotoh
 1 /usr/local/texlive/2018/texmf-dist/doc/latex/gotoh/gotoh.pdf
   = Package documentation
 2 /usr/local/texlive/2018/texmf-dist/doc/latex/gotoh/README.md
   = Readme
texdoc -lI gotoh  0.67s user 0.03s system 93% cpu 0.743 total
```

Here, without the cache, it takes about four times more than with the cache file.
(On a lower spec cmputer, it may take more than this, which I guess enough painful)

I will think about dropping the cache file in the future, but before that, I want to make the tlpdb parser faster.

cf. Section "Using tlpdb" in the TODO.md

**Comment by kberry** [comment]
By now texdoc creates new cache files whenever the tlpd changes
    (even in version 3.0). Didn't we discuss that we drop the cache
    generation and always use the tlpdb directly?

The Data.tlpdb.lua stuff that got removed was separate from the TEXMFVAR
(or wherever it is) cache. As Takuto says, having a predigested Lua
cache is necessary in practice.

I am skeptical that parsing a 12mb file can ever be fast enough to do
per-invocation. Even if it was with a compiled program, let alone with
Lua. -k

**Comment by norbusan** [comment]
Hmm, indeed. I need to look into the current parsing code. But it probably wont get faster.

**Comment by norbusan** [comment]
For now closing this issue, irrelevant.
