### ISSUE TITLE
[feature] Can texdoc has a shell completion for bash/zsh/...?

### ISSUE THREAD

**Issue by Freed-Wu** [TeX-Live/texdoc#89]
That is, user can `eval $(texdoc --print-completion XXsh)` in their bashrc/zshrc then

```
$ texdoc -<TAB>
option
-c             Set configuration item NAME to VALUE.
-D             Activate all debug output (equal to "--debug=all").
--debug        Activate all debug output (equal to "--debug=all").
-d             LIST, --debug=LIST
--files        Print the list of configuration files used.
...
```

TIA!

**Comment by wtsnjp** [comment]
Please refer to our wiki: https://github.com/TeX-Live/texdoc/wiki/Tab-completion

**Comment by Freed-Wu** [comment]
Oh, I thought the code stores the option names and option help text in a data structure, then use the data structure to parse command line input and generate
help text from a template. If so, we can generate completion script from
a template and add a new option to print the script like
`--help` to print help text. However, there doesn't exist this data structure.
This code just use a written manually help text
<https://github.com/TeX-Live/texdoc/blob/master/script/texdoclib-const.tlu#L38-L58>
And parse command line input by many if-clauses in
<https://github.com/TeX-Live/texdoc/blob/master/script/texdoclib-cli.tlu#L101-L146>

So I think if it is hard to generate shell scripts except there are some one would
rather to write one manually like
<https://gist.github.com/wtsnjp/07d2b4acb04d5286d12d10d6021c2716>. And this
written manually script must be updated when the new option be added, which is
usually out-of-time, compared to the script generated from a template.

**Comment by Freed-Wu** [comment]
<https://github.com/latex3/l3build/blob/main/l3build-arguments.lua#L37-L163> is the data structure I mentioned.
<https://github.com/latex3/l3build/blob/main/l3build-help.lua#L41-L93> is using the data structure to generate help text.
<https://github.com/latex3/l3build/blob/main/l3build-help.lua#L41-L93> is using the data structure to generate shell completion.

**Comment by wtsnjp** [comment]
Thanks for providing the details of your request and also pointers to the existing project, l3build.

Having a data structure of the command-line options is feasible. It is also possible to support a new option to generate the shell completion script. However, supporting multiple shells such as bash, csh, zsh, fish, and so on can be costly. Choosing one or two shells with a good reason might be difficult. Since most of the tools in TeX Live do not have such a feature, I wonder if only a few TeX Live users will use the feature. I don't want to have that burden directly in this project unless many people request it. Besides, this can be just done outside of this project.

(Hereafter, off-topic for this project)

The [zsh completion function](https://gist.github.com/wtsnjp/07d2b4acb04d5286d12d10d6021c2716) that I personally maintain is currently hosted at https://github.com/wtsnjp/texlive-completions.

As a maintainer of Texdoc, I am maintaining the script according to Texdoc updates for the time being, so please do not worry too much about that script will be outdated.

**Comment by Freed-Wu** [comment]
> Having a data structure of the command-line options is feasible.

:+1:

> Choosing one or two shells with a good reason might be difficult.

I think it should be: if a shell user wants to support a shell, he will contribute code to this project. Not the maintainers support all shells by themselves. Because:

1. The maintainers of the project are not possible to be familiar to all shells.
2. If not any shell user contribute code, it proves the shell don't have enough value to be supported. That is a reason why some shells are supported and why some shells are not supported. (The reason is not difficult at all, really? :smile:)

> The zsh completion function that I personally maintain is currently hosted

I suggest pushing it to [zsh-completions](https://github.com/zsh-users/zsh-completions/).

**Comment by Freed-Wu** [comment]
Is there any project about a data structure of the command-line?

**Comment by wtsnjp** [comment]
No, there isn't. You can include that part also to the pull request if you have a plan.

**Comment by Freed-Wu** [comment]
I'm glad to see this completion have been accepted by many Linux distributions.

- [Archlinux](https://gitlab.archlinux.org/archlinux/packaging/packages/texlive-texmf/-/blob/main/PKGBUILD?ref_type=heads#L237)
- [NixOS](https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/tools/typesetting/tex/texlive/tlpdb-overrides.nix#L369-L379)
