### ISSUE TITLE
4.0: Is opening doc with negative score disabled?

### ISSUE THREAD

**Issue by muzimuzhi** [TeX-Live/texdoc#94]
With Texdoc 3.4.1 (2022-03-19),
- `texdoc topic` opens `TeXbyTopic.pdf`
- `texdoc pdfmeta` opens `l3pdfmeta.pdf`

With Texdoc 4.0 (2023-02-20),
- both `texdoc topic` and `texdoc pdfmeta` open nothing but give a prompt like
```
$ texdoc topic
Unfortunately, there are no good matches for "topic".

Here are the top three matches:
    1 plain/texbytopic/TeXbyTopic.pdf
    2 plain/texbytopic/README
    3 <empty>

There may be online documentation available for "topic" at
    https://texdoc.org/serve/topic/0
This documentation may be for a different version than you have installed.

Enter number of file to view, Y to search online, or any other key to exit:
```
The scores remain changed between versions
```
$ texdoc -lM topic
topic	-8.5	/usr/local/texlive/2022basic/texmf-dist/doc/plain/texbytopic/TeXbyTopic.pdf		The book itself
topic	-9.8	/usr/local/texlive/2022basic/texmf-dist/doc/plain/texbytopic/README		Readme
$ texdoc -lM pdfmeta
pdfmeta	-10.0	/usr/local/texlive/2022basic/texmf-dist/doc/latex/pdfmanagement-testphase/l3pdfmeta.pdf
```

**Comment by wtsnjp** [comment]
The answer to your question can be yes or no, depending on what you focus on. This is an intentional change introduced in #79.

Since a search result with a negative score is, by definition, a "bad" result, we decided it was better to ask the user if they want to open or search online rather than immediately open the top file.

It is not the case that the feature is completely disabled since local files with such "bad" results can also be opened if you type in the numbers as the prompt indicates.

Also, if you specify `--nointeract` (`-I`) on the command line, the "bad" results will still be opened immediately without prompting.

```shell
$ texdoc -I topic
```

**Comment by muzimuzhi** [comment]
> The answer to your question can be yes or no, depending on what you focus on. This is an intentional change introduced in #79.

Oh this is a documented breaking change.  Sorry, I didn't read/find the corresponding doc paragraphs myself.

Don't know as a partial-doc-name lover, how minority I am.  For now I'll add aliases to user `texdoc.cnf` for partial doc names I frequently use.  Thanks for all your work and help.

**Comment by kberry** [comment]
I suggest that the final query
```
Enter number of file to view, Y to search online, or any other key to exit:
```
have another option (one way or another) to allow viewing the whole list.
